services:

  postgres:
    image: postgres:17

    container_name: jobscheduler-postgres

    environment:
      POSTGRES_DB: job_scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d job_scheduler"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jobscheduler-app

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/job_scheduler
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: