CREATE TABLE scheduled_jobs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    description VARCHAR(500),

    job_type VARCHAR(255) NOT NULL,

    payload TEXT,

    status VARCHAR(50) NOT NULL,

    scheduled_time TIMESTAMP NOT NULL,

    next_run_at TIMESTAMP,

    retry_count INTEGER NOT NULL DEFAULT 0,

    max_retries INTEGER NOT NULL DEFAULT 3,

    last_error VARCHAR(255),

    created_at TIMESTAMP,

    updated_at TIMESTAMP,

    executed_at TIMESTAMP,

    completed_at TIMESTAMP
);


CREATE TABLE job_execution_history (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_id BIGINT NOT NULL,

    attempt_number INTEGER NOT NULL,

    status VARCHAR(50) NOT NULL,

    started_at TIMESTAMP NOT NULL,

    completed_at TIMESTAMP,

    error_message TEXT,

    CONSTRAINT fk_job_execution_history_job
        FOREIGN KEY (job_id)
        REFERENCES scheduled_jobs(id)
        ON DELETE CASCADE
);